server:
  port: 8888

logging:
  file:
    name: mylog.log
    path: logs

spring:
  application:
    name: myTest
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.111.157:3306/wltest
    username: root
    password: WLl@1234

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*



