server:
  port: 8888

logging:
  file:
    path: logs
    name: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.111.157:3306/wltest1
    #url: jdbc:mysql://192.168.111.157:3306/wltest1?serverTimezone=GMT
    username: root
    password: WLl@1234

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*